development:
  adapter: postgresql
  encoding: unicode
  database: pg_mastery_development
  username: rails_user
  password: password
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  encoding: unicode
  database: pg_mastery_test
  username: rails_user
  password: password
  pool: 5
  timeout: 5000

# omit production config since this is running on Heroku